name: Makefile CI

on:
  push:
    branches:
      - release/*
  pull_request:
    branches: [ main, stable* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup NPM and Node
      uses: skjnldsv/read-package-engines-version-actions@v1.1
      id: versions
      with:
        fallbackNpm: '^7'
        fallbackNode: '^14'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: make
    
    - name: Creating artifact
      run: make source

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Workspace
        path: ./build/artifacts/source/workspace.tar.gz
