name: Makefile CI

on:
  push:
    branches:
      - release/*
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
    
    - name: Creating artifact
      run: make source

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Workspace
        path: ./build/artifacts/source/workspace.tar.gz
