# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 15, 16 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read package.json for npm engine version only
        uses: skjnldsv/read-package-engines-version-actions@v1.1
        id: versions
        with:
          fallbackNpm: '^7'
          fallbackNode: '^14'

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}"
        run: npm i -g npm@${{ steps.versions.outputs.npmVersion }}

      - name: Use Node.js ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Debug npm
        run: npm --version

      - name: Install all dependencies
        run: npm ci -f

      - name: Build the project
        run: npm run build --if-present

      - name: Run all tests
        run: npm test