name: PHP Composer

on:
  push:
    branches: [ main, stable* ]
  pull_request:
    branches: [ main, stable* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [8.2]
        nextcloud-versions: ['stable28', 'master']
        include:
            - php: 8.2
              nextcloud-version: master

    name: Nextcloud ${{ matrix.nextcloud-versions }} php${{ matrix.php-versions }} unit tests
    steps:
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer:v2
        extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip,gmp
        coverage: xdebug
    - name: Checkout Nextcloud
      run: git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b ${{ matrix.nextcloud-versions }} nextcloud
    - name: Install Nextcloud
      run: php -f nextcloud/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
    - name: Checkout workspace
      uses: actions/checkout@main
      with:
        path: nextcloud/apps/workspace
    - name: Validate composer.json and composer.lock
      working-directory: nextcloud/apps/workspace
      run: composer validate --strict
    - name: Install dependencies
      working-directory: nextcloud/apps/workspace
      run: composer install --prefer-dist --no-progress
    - name: Check coding standards
      working-directory: nextcloud/apps/workspace
      run: composer run-script cs:check
    - name: Run test suite
      working-directory: nextcloud/apps/workspace
      run: composer run-script test
